[params]

[params.px4_fusion]
mode = "hil"

[params.px4_fusion.hil]
hil_sensor_rate_hz = 250.0
mag_rate_hz = 84.0
baro_rate_hz = 42.0
gps_rate_hz = 5.0

[params.visual_stream]
enabled = true
rate_hz = 120.0
zmq_endpoint = "tcp://0.0.0.0:5602"

[params.fw]
thrust_motor_constant = 8.54858e-06
thrust_moment_constant = 0.01
thrust_time_constant_up = 0.0125
thrust_time_constant_down = 0.025
thrust_max_rot_velocity = 3500.0
thrust_max_relative_airspeed_mps = 80.0
thrust_rotor_drag_coeff = 8.06428e-05
thrust_rolling_moment_coeff = 1e-06
thrust_rotor_direction = 1.0
linear_damping = 0.18
angular_damping = 0.05

[params.fw.segments]
puller_rotor_index = 4
wing_span = 0.94
wing_mac = 0.22
wing_flap_chord = 0.07
wing_ar = 4.2727272727
wing_alpha_0_deg = -4.0
wing_left_pos_b = [-0.02, 0.24, 0.0]
wing_right_pos_b = [-0.02, -0.24, 0.0]
wing_left_dihedral_deg = 3.0
wing_right_dihedral_deg = -3.0
prop_radius = 0.11
tail_span = 0.34
tail_mac = 0.11
tail_alpha_0_deg = 0.0
tail_pos_b = [-0.46, 0.0, 0.01]
tail_dihedral_deg = 0.0
tail_ar = 3.0909090909
tail_flap_chord = 0.05
fin_span = 0.25
fin_mac = 0.18
fin_alpha_0_deg = 0.0
fin_pos_b = [-0.5, 0.0, 0.08]
fin_dihedral_deg = -90.0
fin_ar = 1.3888888889
fin_flap_chord = 0.1
fuselage_span = 0.18
fuselage_mac = 0.75
fuselage_alpha_0_deg = 0.0
fuselage_pos_b = [0.0, 0.0, 0.0]
fuselage_dihedral_deg = -90.0
