[params]

[params.px4_fusion]
mode = "hil"

[params.px4_fusion.hil]
hil_sensor_rate_hz = 250.0
mag_rate_hz = 100.0
baro_rate_hz = 50.0
gps_rate_hz = 30.0

[params.px4_fusion.delay]
hil_sensor_delay_ms = [0.0, 0.0]
vision_delay_ms = [0.0, 0.0]
actuator_delay_ms = [0.0, 0.0]

[params.visual_stream]
enabled = true
rate_hz = 120.0
zmq_endpoint = "tcp://0.0.0.0:5601"

[params.fw]
model = "standard_vtol"
thrust_motor_constant = 8.54858e-06
thrust_moment_constant = 0.01
thrust_time_constant_up = 0.0125
thrust_time_constant_down = 0.025
thrust_max_rot_velocity = 3500.0
thrust_max_relative_airspeed_mps = 30.0
thrust_rotor_drag_coeff = 1.06428e-04
thrust_rolling_moment_coeff = 1e-06
thrust_rotor_direction = 1.0
linear_damping = 0.0
angular_damping = 0.0

[params.fw.controls]
throttle_channel_index = 4
surface_channel_indices = [-1, -1, -1, 5, 6, 7]
surface_channel_signs = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

[[params.fw.lift_surfaces]]
joint_name = "left_elevon_joint"
cp = [-0.05, 0.3, 0.05]
area = 0.50
a0 = 0.05984281113
cla = 4.752798721
cda = 0.6417112299
cma = 0.0
alpha_stall = 0.3391428111
cla_stall = -3.85
cda_stall = -0.9233984055
cma_stall = 0.0
control_joint_rad_to_cl = -1.0

[[params.fw.lift_surfaces]]
joint_name = "right_elevon_joint"
cp = [-0.05, -0.3, 0.05]
area = 0.50
a0 = 0.05984281113
cla = 4.752798721
cda = 0.6417112299
cma = 0.0
alpha_stall = 0.3391428111
cla_stall = -3.85
cda_stall = -0.9233984055
cma_stall = 0.0
control_joint_rad_to_cl = -1.0

[[params.fw.lift_surfaces]]
joint_name = "elevator_joint"
cp = [-0.5, 0.0, 0.0]
area = 0.01
a0 = -0.2
cla = 4.752798721
cda = 0.6417112299
cma = 0.0
alpha_stall = 0.3391428111
cla_stall = -3.85
cda_stall = -0.9233984055
cma_stall = 0.0
control_joint_rad_to_cl = -12.0

[params.vtol]
lift_rotor_indices = [0, 1, 2, 3]
rotor_direction = [1.0, 1.0, -1.0, -1.0]
motor_constant = 2e-05
moment_constant = 0.06
rotor_drag_coeff = 1.06428e-04
rolling_moment_coeff = 1e-06
time_constant_up = 0.0125
time_constant_down = 0.025
max_rot_velocity = 1500.0
puller_rotor_index = 4
